### ISSUE TITLE
"entered" signal is not emitted & trigger is flushed when StateMachinePlayer started

### ISSUE THREAD

**Issue by turbohz** [imjp94/gd-YAFSM#24]
Perhaps this is by design? Is it only to be used for nested fsms?

According to the docs: 

> - entered(to) # Entry of state machine(including nested), empty string equals to root

**Comment by imjp94** [comment]
This is a bug caused by [StateMachinePlayer.gd at line 174](https://github.com/imjp94/gd-YAFSM/blob/master/addons/imjp94.yafsm/src/StateMachinePlayer.gd#L174) where the initial stated was "manually" set, therefore it doesn't emit any signal.

The workarounds is fairly simple, just insert `emit_signal("entered", "")` below line 174:
```gdscript
func start():
	push(State.ENTRY_STATE)
	emit_signal("entered", "")
	_was_transited = true
```
