### ISSUE TITLE
StateMachine resource corrupted after dragging transition line to itself

### ISSUE THREAD

**Issue by SirPigeonz** [imjp94/gd-YAFSM#5]
Hi :)
While testing your addon I found that there might be some bugs with SM resource transitions editing.
If you delete the transition the SM resource is corrupted somehow, and it looses transitions if you switch to the other node or restart the project.

Test Project: 
[gd-YAFSM_test.zip](https://github.com/imjp94/gd-YAFSM/files/5978561/gd-YAFSM_test.zip)

How to reproduce:
- open example project
- in StateMachine Player node
- create transition from State3 to State4
- select root Node2D
- select StateMachinePlayer node again

What happens: the transition that you just created disappears.

I also get errors: 
![obraz](https://user-images.githubusercontent.com/6152134/107889659-7ea98500-6f14-11eb-857b-8205d86a1e52.png)

Let me know if you will need more info :)

Cheers!

**Comment by imjp94** [comment]
After debugging the resource in .tres format, it turns out that the transition doesn't get properly removed, instead, it is transiting to self.
![Screenshot 2021-02-15 060023](https://user-images.githubusercontent.com/11486079/107890335-61e07200-6f53-11eb-9013-226e2f82f08e.png)

Which is really weird, as there's no way to connect to self in the editor. 
I can confirm this bug, but I can't reproduce it through deleting other transition or replicate the whole StateMachine(then delete transition from State3 to State4). 

Do you still happen to remember the steps to create the same bug?
or 
Will you still get the same bug, after replicate the StateMachine resource and delete the transition?

**Comment by SirPigeonz** [comment]
Good news. I managed to figure out what is the couse of this bug :)

This:
> [sub_resource type="Resource" id=6]
> script = ExtResource( 3 )
> from = "State"
> to = "State"
> conditions = {
> 
> }

I managed to connect the state to itself ;)

I thought you can delete transitions by draging them away, turns out I just created transition that should be valid this way.
It's not visible in graph because line is probably 0px

**Comment by SirPigeonz** [comment]
Lol we posted the same time xD

**Comment by SirPigeonz** [comment]
You have to create a transition to the other state, then drag it out to the parent state itself :D

**Comment by imjp94** [comment]
> > Do you still happen to remember the steps to create the same bug?
> 
> You have to create a transition to the other state, then drag it out to the parent state itself :D

Mind blown, I didn't know such "feature" exist XD

I will fix it once I am free, since it is not a critical bug.
But now there's 2 ways of doing it:
1) Make it to work as you expected, disconnect when reconnect to self
2) Cancel the action (just like dragging the transition to empty space)

What do you think?

**Comment by SirPigeonz** [comment]
I think the best option would be to cancel the action like when dragging to empty space.
Delete button is much more obvious way of deleting stuff ;D

It could lead to annoying behavior when somebody would accidentally drag a transition on the parent and delete it by accident, when his intent was to reconnect it to the other state.

**Comment by imjp94** [comment]
Sounds great, thanks for the feedback!

**Comment by SirPigeonz** [comment]
Thanks for a great add-on ;P
