### ISSUE TITLE
There is a rendering problem in Godot 4.1.1

### ISSUE THREAD

**Issue by dawnrs** [imjp94/gd-YAFSM#65]
When I open the StateMachine page, this error will be reported many times

`"servers/rendering/renderer_canvas_cull.cpp:1084 - Condition "p_colors.size() != 1 && p_colors.size() * 2 != p_points.size()" is true."`

My Godot version is 4.1.1 and the version of FSM plugin I used is 0.6.1.

Thanks for any help.

**Comment by ODtian** [comment]
I think this's the problem
https://github.com/imjp94/gd-YAFSM/blob/2211a58e8131a530f4e81ffa8854d51b674f36cb/addons/imjp94.yafsm/scenes/flowchart/FlowChartGrid.gd#L45-L64
the code `multi_line_color_array.append(color) ` at line 45-48 and 61-64 appears twice, which is incorrect since you only assign 1 color for each segment of lines(2 points), the size of points array should be 2 times as much as the size of colors array.

**Comment by dawnrs** [comment]
@ODtian 
Thank you for your help， I solve this problem.

**Comment by imjp94** [comment]
Just merge the fix #66 into master branch

Thank you @dawnrs and @ODtian =)
