### ISSUE TITLE
StateMachinePlayer doesn't have a class_name, disallowing static typing

### ISSUE THREAD

**Issue by spiralhalo** [imjp94/gd-YAFSM#83]
I like having static typing. Less error prone.

In godot, it also make autocomplete work deeper than 1 level.

With variant:

![image](https://github.com/user-attachments/assets/a6be99fa-b1cb-4261-bae8-b128b2158e56)

![image](https://github.com/user-attachments/assets/3006f520-9e8b-4501-9779-ae6e49f4d027)

With static typing:

![image](https://github.com/user-attachments/assets/7eb032b0-5dee-4e06-bcc1-5dad810b2abd)

Static typing aside, I also would like to do as many thing from code as possible in general, without relying on the node tree / node tab. Having a class name would help with that.

**Comment by ianmckenna87** [comment]
i second this

**Comment by murilosr** [comment]
You can use the class with preload like this to add the StateMachinePlayer type to a script:

```gdscript
const StateMachinePlayer = preload("res://addons/imjp94.yafsm/src/StateMachinePlayer.gd")
```

But doing this in every script is boilerplate code. I added PR #84 which adds class_name to StateMachinePlayer, because it is very useful in scripts. The counterpart is that in Create New Node window it appears as a child of StackPlayer script, but this can be easily ignored.

Also, in my project I needed to extend the StateMachinePlayer, and the StateMachine Debugger was broken. I also fixed it in this PR.

If you want, you can clone the forked repo from [here](https://github.com/murilosr/gd-YAFSM/tree/master)
It is the same source code with these two changes.

**Comment by ianmckenna87** [comment]
brilliant, thanks!

**Comment by murilosr** [comment]
@ianmckenna87 I agree. An assertion there would be good to warn the user that State Machine is required (or even show the warning icon at the Node tree on Editor, given that StateMachinePlayer is already a @tool script).
I'll make these changes and upload them to my fork. If everything works, I'll try to PR here.

**Comment by murilosr** [comment]
@ianmckenna87 new PR #85 with the assertions and [feedbacks](https://github.com/imjp94/gd-YAFSM/pull/85#issuecomment-2408607841) proposed ([fork](https://github.com/murilosr/gd-YAFSM/tree/master) is also updated, together with class_name addition)
